### ISSUE TITLE
read.annotated.[tree|nexux] incorrectly handles branch-specific traits

### ISSUE THREAD

**Issue by msuchard** [thibautjombart/OutbreakTools#1]
BEAST has changed its annotation scheme to differentiate between node-specific and branch-specific traits.  Currently branch-specific traits are incorrectly handled.

**Comment by msuchard** [comment]
Fixed via b632d670c7d40d2199cb9f01ebaa78f453f7a014

**Comment by thibautjombart** [comment]
Great!
