### ISSUE TITLE
read.annotated.nexus mixes up the tip labels

### ISSUE THREAD

**Issue by fmichonneau** [thibautjombart/OutbreakTools#2]
I haven't had a  chance to investigate fully to figure out the underlying cause, but reading the tree files generated directly from treeannotator mixes up the tip labels (they are assigned to the wrong tip). However, reading tree files using the "export tree" function in FigTree have the labels correctly assigned.

**Comment by thibautjombart** [comment]
I think similar problems have been reported before, but I thought they had been fixed.
@msuchard might have a chance to check?
@fmichonneau can you post a reproducible example?

**Comment by fmichonneau** [comment]
Here are two files: https://gist.github.com/fmichonneau/0d1c3104a89332adff57

`tt.nex` is the output from treeannotator while `tt_exported.nex` is what figtree produces when opening `tt.nex` and exporting it (File > Export Trees, choose NEXUS and check 'include annotations')

When reading these files with `read.annotated.nexus`, the tips are incorrectly labeled when reading in `tt.nex`

![rplot001](https://cloud.githubusercontent.com/assets/5502922/10895679/729fca6e-8183-11e5-83a4-2c3d917bd910.png)

I think the code used by `ape` to map taxa to the number they are represented with in the newick string isn't very robust. You may want to consider looking into [rncl](https://github.com/fmichonneau/rncl) to parse the NEXUS file (without the annotations) as it relies on the NEXUS Class Library (written in C++) which is much more robust and mature. Full disclaimer, I'm the maintainer of `rncl`.

**Comment by msuchard** [comment]
Thank you very much for the examples.  I'll dig into this.

**Comment by msuchard** [comment]
On preliminary glance, the error appears fixed currently in HEAD.  However, there remains a small issue with inconsistencies in labeling the root node when the root has no branch-length (TreeAnnotator output).  I'll have some time in the next few days to patch.

Re: `rnc`l, am happy to refactor to use this package instead.

**Comment by msuchard** [comment]
Commit 9dc545caa14ed36399e00d76c45f59c023fd2a07 seems to solve the 0 root-edge length trouble.  @fmichonneau, are you using `TreeAnnotator` from `BEAST2`?    

The following script appears to work for me:

``` r
devtools::install_github("thibautjombart/OutbreakTools")

library(OutbreakTools)
library(testthat)

t1 <- read.annotated.nexus("tt.nex")
t2 <- read.annotated.nexus("tt_exported.nex")

# Check that the same tree and traits results
expect_equal(names(t1), names(t2))
expect_equal(t1$edge, t2$edge)
expect_equal(t1$Nnode, t2$Nnode)
expect_equal(t1$tip.label, t2$tip.label)
expect_equal(t1$edge.length, t2$edge.length, tolerance = 1E-4)
expect_equal(t1$root.annotation, t2$root.annotation)
expect_equal(t1$annotations, t2$annotations)

# Visual check
plot(t1)
plot(t2)
```

**Comment by fmichonneau** [comment]
Yes, I used BEAST2. I was however using the CRAN version of OutbreakTools. Thanks for fixing it!
