### ISSUE TITLE
Problems installing on Mac

### ISSUE THREAD

**Issue by KrzysztofMKozak** [thibautjombart/OutbreakTools#4]
Hello,

I am attempting an installation using R 3.6. On two different Mac machines it fails with the following error message. reinstalling ape does not help.

** byte-compile and prepare package for lazy loading
Error: objects ‘c.multiPhylo’, ‘[.multiPhylo’, ‘[[<-.multiPhylo’, ‘[[.multiPhylo’, ‘$<-.multiPhylo’, ‘$.multiPhylo’, ‘print.multiPhylo’ are not exported by 'namespace:ape'
Execution halted
ERROR: lazy loading failed for package ‘OutbreakTools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/OutbreakTools’
Error: Failed to install 'OutbreakTools' from GitHub:
  (converted from warning) installation of package ‘/var/folders/3x/xxz1kl0n2jj08x5y1gktfs_m0000gn/T//RtmpQbpOxO/file9a4e4dc81ee5/OutbreakTools_0.1-16.tar.gz’ had non-zero exit status

**Comment by thibautjombart** [comment]
Hello, 
unfortunately the package is no longer maintained, and has been removed from CRAN. For replacements, please check the RECON packages:
http://repidemicsconsortium.org/

**Comment by KrzysztofMKozak** [comment]
Dear Thibaut,

OK, thanks for the clarification. Unfortunately it was a dependency for
interpreting the results from the AIM package in BEAST2 (plotting gene flow
patterns). Ah well, will need to figure out another solution.

Best,
__
Chris Kozak
